name: cx

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
jobs:
  ast_scan:
    runs-on: ubuntu-latest
    name: Checkmarx scan run
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://us.ast.checkmarx.net/
          cx_tenant: workshop
          cx_api_key: ${{ secrets.CX_API_KEY }}
   
