name: cx

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ast_scan:
    runs-on: ubuntu-latest
    name: Checkmarx scan run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: workshop
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --report-format json,sbom --report-sbom-format CycloneDxJson --output-name sean_results --output-path ./results/ --output-name sean_sbom --output-path ./results/
          
