name: cx
on:
  # pull_request:
  #   branches:
  #     - master
    push:
      branches:
      -master
jobs:
  ast_scan:
    runs-on: ubuntu-latest
    name: Checkmarx scan run
    steps:
        # - name: Run scan
        # uses: CheckmarxDev/ast-github-action@more_engines
        # id: scan
        # with:
        #   github_repo_token: ${{ secrets.GITHUB_TOKEN }}
        #   ast_uri: ${{ secrets.AST_URI }}
        #   ast_access_key_id: ${{ secrets.AST_ACCESS_KEY_ID }}
        #   ast_access_key_secret: ${{ secrets.AST_ACCESS_KEY_SECRET }}
        #   sca_user: ${{ secrets.SCA_USER }}
        #   sca_password: ${{ secrets.SCA_PASSWORD }}
        #   action_scan_complete_timeout_secs: 600
        #   high_results_threshold: 0
        #   medium_results_threshold: 10
        - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: workshop 
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
